spellchecker: aspell
matrix:
- name: python
  sources:
    - beginner_source/*.py
    - intermediate_source/*.py
    #- intermediate_source/autograd_saved_tensors_hooks_tutorial.py
    #- intermediate_source/ax_multiobjective_nas_tutorial.py
    #- intermediate_source/char_rnn_classification_tutorial.py
    #- intermediate_source/char_rnn_generation_tutorial.py
    #- intermediate_source/custom_function_conv_bn_tutorial.py
    #- intermediate_source/ensembling.py
    #- intermediate_source/flask_rest_api_tutorial.py
    #- intermediate_source/forward_ad_usage.py
    #- intermediate_source/fx_conv_bn_fuser.py
    #- intermediate_source/fx_profiling_tutorial.py
    #- intermediate_source/jacobians_hessians.py
    #- intermediate_source/mario_rl_tutorial.py
    #- intermediate_source/mnist_train_nas.py
    #- intermediate_source/memory_format_tutorial.py
    #- intermediate_source/model_parallel_tutorial.py
    #- intermediate_source/neural_tangent_kernels.py
    #- intermediate_source/nvfuser_intro_tutorial.py
    #- intermediate_source/parametrizations.py
    #- intermediate_source/per_sample_grads.py
    #- intermediate_source/pipeline_tutorial.py
    #- intermediate_source/pruning_tutorial.py
    #- intermediate_source/reinforcement_ppo.py
    #- intermediate_source/reinforcement_q_learning.py
    #- intermediate_source/scaled_dot_product_attention_tutorial.py
    #- intermediate_source/seq2seq_translation_tutorial.py
    #- intermediate_source/spatial_transformer_tutorial.py
    #- intermediate_source/tensorboard_profiler_tutorial.py
    #- intermediate_source/torch_compile_tutorial.py
  dictionary:
    wordlists:
      - en-wordlist.txt
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # Exclude figure rST tags
        - open: '\.\.\s+(figure|literalinclude|math|image|grid)::'
          close: '\n'
        # Exclude roles:
        - open: ':(?:(class|py:mod|mod|func)):`'
          content: '[^`]*'
          close: '`'
        # Exclude raw directive
        - open: '\.\. (raw)::.*$\n*'
          close: '\n'
        # Exclude
        - open: '.*(:py:mod:).*'
          close: ' '
        # Exclude Python coding directives
        - open: '-\*- coding:'
          close: '\n'
        # Exclude Authors:
        - open: 'Author(|s):'
          close: '\n'
        # Exclude .rst directives:
        - open: ':math:`.*`'
          close: ' '
        # Ignore multiline content in codeblock
        - open: '(?s)^::\n\n  '
          close: '^\n'
        # Ignore reStructuredText block directives
        - open: '\.\. (code-block|math)::.*$\n*'
          content: '(?P<first>(^(?P<indent>[ ]+).*$\n))(?P<other>(^([ \t]+.*|[ \t]*)$\n)*)'
          close: '(^(?![ \t]+.*$))'
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      ignores:
        - code
        - pre
  - pyspelling.filters.url:
