install_official_git_client: &install_official_git_client
  name: Install Official Git Client
  no_output_timeout: "1h"
  command: |
    set -e
    sudo apt-get -qq update
    sudo apt-get -qq install openssh-client git

pytorch_tutorial_build_defaults: &pytorch_tutorial_build_defaults
  machine:
    image: default
  steps:
  - checkout
  - run:
      name: Set Up CI Environment
      no_output_timeout: "1h"
      command: |
        set -e

        curl -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
        echo "deb https://nvidia.github.io/libnvidia-container/ubuntu14.04/amd64 /" | sudo tee -a /etc/apt/sources.list.d/nvidia-docker.list
        echo "deb https://nvidia.github.io/nvidia-container-runtime/ubuntu14.04/amd64 /" | sudo tee -a /etc/apt/sources.list.d/nvidia-docker.list
        echo "deb https://nvidia.github.io/nvidia-docker/ubuntu14.04/amd64 /" | sudo tee -a /etc/apt/sources.list.d/nvidia-docker.list

        sudo apt-get -qq update
        sudo apt-get -qq remove linux-image-generic linux-headers-generic linux-generic
        sudo apt-get -qq install \
          linux-headers-$(uname -r) \
          linux-image-generic \
          moreutils \
          nvidia-docker2 \
          expect-dev

        sudo pkill -SIGHUP dockerd

        sudo pip -q install awscli==1.16.35

        if [ -n "${CUDA_VERSION}" ]; then
          wget 'https://s3.amazonaws.com/ossci-linux/nvidia_driver/NVIDIA-Linux-x86_64-396.26.run'
          sudo /bin/bash ./NVIDIA-Linux-x86_64-396.26.run -s --no-drm
          nvidia-smi
        fi

        # This IAM user only allows read-write access to ECR
        export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_ECR_READ_ONLY}
        export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_ECR_READ_ONLY}
        eval $(aws ecr get-login --region us-east-1 --no-include-email)
  - run:
      name: Build
      no_output_timeout: "20h"
      command: |
        set -e
        cat >/home/circleci/project/ci_build_script.sh <<EOL
        # =================== The following code will be executed inside Docker container ===================
        set -ex

        pip install awscli==1.16.35
        pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu80/torch_nightly.html

        .jenkins/build.sh

        if [[ "${JOB_BASE_NAME}" == *master ]]; then
          7z a master.7z docs
          aws s3 cp master.7z s3://pytorch-tutorial-build-pull-request/${COMMIT_ID}/master.7z
        fi
        # =================== The above code will be executed inside Docker container ===================
        EOL
        chmod +x /home/circleci/project/ci_build_script.sh

        echo "DOCKER_IMAGE: "${DOCKER_IMAGE}
        docker pull ${DOCKER_IMAGE} >/dev/null
        if [ -n "${CUDA_VERSION}" ]; then
          export id=$(docker run --runtime=nvidia -t -d -w /var/lib/jenkins ${DOCKER_IMAGE})
        else
          export id=$(docker run -t -d -w /var/lib/jenkins ${DOCKER_IMAGE})
        fi

        echo "declare -x JOB_BASE_NAME=${JOB_BASE_NAME}" > /home/circleci/project/env
        echo "declare -x COMMIT_ID=${CIRCLE_SHA1}" >> /home/circleci/project/env
        echo "declare -x AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_PYTORCH_TUTORIAL_BUILD_PR_S3_BUCKET}" >> /home/circleci/project/env
        echo "declare -x AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_PYTORCH_TUTORIAL_BUILD_PR_S3_BUCKET}" >> /home/circleci/project/env

        docker cp /home/circleci/project/. "$id:/var/lib/jenkins/workspace"

        export COMMAND='((echo "source ./workspace/env" && echo "sudo chown -R jenkins workspace && cd workspace && ./ci_build_script.sh") | docker exec -u jenkins -i "$id" bash) 2>&1'
        echo ${COMMAND} > ./command.sh && unbuffer bash ./command.sh | ts

version: 2
jobs:
  pytorch_tutorial_build_pr_worker_0:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    branches:
      ignore:
        - master
    resource_class: gpu.medium
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-0
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_1:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-1
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_2:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-2
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_3:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-3
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_4:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-4
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_5:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-5
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_6:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-6
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_7:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-7
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_8:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-8
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_9:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-9
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_10:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-10
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_11:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-11
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_12:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-12
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_13:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-13
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_14:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-14
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_15:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-15
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_16:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-16
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_17:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-17
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_18:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-18
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_worker_19:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-worker-19
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
      CUDA_VERSION: "8"
    resource_class: gpu.medium
    <<: *pytorch_tutorial_build_defaults

  pytorch_tutorial_build_master:
    environment:
      JOB_BASE_NAME: pytorch-tutorial-build-master
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda8-cudnn6-py3:latest"
    resource_class: medium
    <<: *pytorch_tutorial_build_defaults

workflows:
  version: 2
  build:
    jobs:
      - pytorch_tutorial_build_worker_0
      - pytorch_tutorial_build_worker_1
      - pytorch_tutorial_build_worker_2
      - pytorch_tutorial_build_worker_3
      - pytorch_tutorial_build_worker_4
      - pytorch_tutorial_build_worker_5
      - pytorch_tutorial_build_worker_6
      - pytorch_tutorial_build_worker_7
      - pytorch_tutorial_build_worker_8
      - pytorch_tutorial_build_worker_9
      - pytorch_tutorial_build_worker_10
      - pytorch_tutorial_build_worker_11
      - pytorch_tutorial_build_worker_12
      - pytorch_tutorial_build_worker_13
      - pytorch_tutorial_build_worker_14
      - pytorch_tutorial_build_worker_15
      - pytorch_tutorial_build_worker_16
      - pytorch_tutorial_build_worker_17
      - pytorch_tutorial_build_worker_18
      - pytorch_tutorial_build_worker_19
      - pytorch_tutorial_build_master
